ALTER TABLE users
    ADD COLUMN IF NOT EXISTS school VARCHAR(128),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(32),
    ADD COLUMN IF NOT EXISTS email VARCHAR(128),
    ADD COLUMN IF NOT EXISTS bio VARCHAR(512);
